#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
mkdir -p bin
rm -f bin/makefont.js bin/server.js bin/bundle.js
echo "build src/makefont.ls -> bin/makefont.js"
echo "#!/usr/bin/env node" > bin/makefont.js
./node_modules/.bin/lsc -cpb src/makefont.ls >> bin/makefont.js
chmod 755 bin/makefont.js
echo "build src/bundle.ls -> bin/bundle.js"
echo "#!/usr/bin/env node" > bin/bundle.js
./node_modules/.bin/lsc -cpb src/bundle.ls >> bin/bundle.js
chmod 755 bin/bundle.js
echo "build src/server.ls -> bin/server.js"
echo "#!/usr/bin/env node" > bin/server.js
./node_modules/.bin/lsc -cpb src/server.ls >> bin/server.js
chmod 755 bin/server.js


echo "Optimize 'line-16-light' SVG Files..."
npx svgo -q -f src/vector-files/line-16/light-svg/ -o dist/line-16-light/svg
echo "Generating 'line-16-light' Font File..."
./bin/makefont.js -u 800 -m src/unicode.json -i dist/line-16-light/svg -a 700 -y -100 -e 100 -d dist/line-16-light

echo "Optimize 'line-24-bold' SVG Files..."
npx svgo -q -f src/vector-files/line-24/bold-svg/ -o dist/line-24-bold/svg
echo "Generating 'line-24-bold' Font File..."
./bin/makefont.js -u 1200 -m src/unicode.json -i dist/line-24-bold/svg -a 1050 -y -150 -e 150 -d dist/line-24-bold

echo "Optimize 'legacy' SVG Files..."
npx svgo -q -f src/vector-files/legacy/svg/ -o dist/legacy/svg
echo "Generating 'legacy' Font File..."
./bin/makefont.js -u 90 -m src/unicode.json -i dist/legacy/svg -a 80 -y -10 -e 10 -d dist/legacy

echo "Make 'line' the default icon set..."
cp -R dist/line-24-bold/* dist

echo "Generating woff2 counterparts..."
cat dist/ldif.ttf | ./node_modules/.bin/ttf2woff2 > dist/ldif.woff2
cat dist/legacy/ldif.ttf | ./node_modules/.bin/ttf2woff2 > dist/legacy/ldif.woff2
cat dist/line-16-light/ldif.ttf | ./node_modules/.bin/ttf2woff2 > dist/line-16-light/ldif.woff2
cat dist/line-24-bold/ldif.ttf | ./node_modules/.bin/ttf2woff2 > dist/line-24-bold/ldif.woff2

echo "bundle font with css ..."
./bin/bundle.js

echo "copy dist to dev web ..."
rm -rf web/static/assets/lib/ldif/dev/
mkdir -p web/static/assets/lib/ldif
cp -R dist web/static/assets/lib/ldif/dev
