#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
mkdir -p bin
echo "build src/makefont.ls -> bin/makefont.js"
rm bin/makefont.js
echo "#!/usr/bin/env node" > bin/makefont.js
./node_modules/.bin/lsc -cpb src/makefont.ls >> bin/makefont.js
chmod 755 bin/makefont.js

echo "Generating Font File..."
./bin/makefont.js -s 90 -m src/unicode.json -i src/svg -a 70 -y '-13' -d dist

echo "copy dist to dev web ..."
rm -rf web/static/assets/lib/ldif/dev/
mkdir -p web/static/assets/lib/ldif
cp -R dist web/static/assets/lib/ldif/dev
#echo "Touch web index file..."
#touch web/src/pug/index.pug
