#!/usr/bin/env bash
rm -rf dist/
mkdir -p dist
echo "build src/base.styl -> dist/ldif.css ..."
./node_modules/.bin/stylus -p src/base.styl > dist/ldif.css
echo "truncate head lines of files/style.css ->> dist/ldif.css..."
tail -n +10 files/style.css >> dist/ldif.css
echo "Uglifying ldif.css..."
uglifycss dist/ldif.css > dist/ldif.min.css
echo "copy font files..."
cp -R files/fonts dist/fonts
echo "done."

